<?php

namespace WDFQVendorFree;

/**
 * @var \WPDesk\Library\FlexibleQuantityCore\WooCommerce\Settings $settings
 */
echo '<div id="dimension_measurements" class="measurement_fields">';
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_pricing', 'value' => $settings['dimension']['pricing']['enabled'], 'class' => 'checkbox _measurement_pricing', 'label' => \__('Show Product Price Per Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to display product pricing per unit on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_dimension_pricing_fields" class="_measurement_pricing_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_dimension_pricing_label', 'value' => $settings['dimension']['pricing']['label'], 'label' => \__('Pricing Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Label to display next to the product price (defaults to pricing unit)', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_dimension_pricing_unit', 'value' => $settings['dimension']['pricing']['unit'], 'class' => '_measurement_pricing_unit', 'label' => \__('Pricing Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['dimension'], 'description' => \__('Unit to define pricing in', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_pricing_calculator_enabled', 'class' => 'checkbox _measurement_pricing_calculator_enabled', 'value' => $settings['dimension']['pricing']['calculator']['enabled'], 'label' => \__('Calculated Price', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define product pricing per unit and allow customers to provide custom measurements', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_pricing_weight_enabled', 'value' => $settings['dimension']['pricing']['weight']['enabled'], 'class' => 'checkbox _measurement_pricing_weight_enabled', 'wrapper_class' => $pricing_weight_wrapper_class . ' _measurement_pricing_calculator_fields', 'label' => \__('Calculated Weight', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define the product weight per unit and calculate the item weight based on the product dimension', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_pricing_inventory_enabled', 'value' => $settings['dimension']['pricing']['inventory']['enabled'], 'class' => 'checkbox _measurement_pricing_inventory_enabled', 'wrapper_class' => 'stock_fields _measurement_pricing_calculator_fields', 'label' => \__('Calculated Inventory', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define inventory per unit and calculate inventory based on the product dimension', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_overage_input('dimension', $settings);
echo '</div>';
echo '<hr/>';
// Dimension - Length
\WDFQVendorFree\fq_price_calculator_wp_radio(['name' => '_measurement_dimension', 'id' => '_measurement_dimension_length', 'rbvalue' => 'length', 'value' => 'yes' == $settings['dimension']['length']['enabled'] ? 'length' : '', 'class' => 'checkbox _measurement_dimension', 'label' => \__('Length', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Select to display the product length in the price calculator', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_dimension_length_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_dimension_length_label', 'value' => $settings['dimension']['length']['label'], 'label' => \__('Length Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Length input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_dimension_length_unit', 'value' => $settings['dimension']['length']['unit'], 'label' => \__('Length Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['dimension'], 'description' => \__('The frontend length input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_length_editable', 'value' => $settings['dimension']['length']['editable'], 'label' => \__('Length Editable', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'class' => 'checkbox _measurement_editable', 'description' => \__('Check this box to allow the needed length to be entered by the customer', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'dimension', 'input_name' => 'length', 'input_label' => \__('Length', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_dimension_length_options']);
\woocommerce_wp_text_input(['id' => '_measurement_dimension_length_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['dimension']['length']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Length Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '</div>';
echo '<hr/>';
// Dimension - Width
\WDFQVendorFree\fq_price_calculator_wp_radio(['name' => '_measurement_dimension', 'id' => '_measurement_dimension_width', 'rbvalue' => 'width', 'value' => 'yes' == $settings['dimension']['width']['enabled'] ? 'width' : '', 'class' => 'checkbox _measurement_dimension', 'label' => \__('Width', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Select to display the product width in the price calculator', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_dimension_width_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_dimension_width_label', 'value' => $settings['dimension']['width']['label'], 'label' => \__('Width Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Width input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_dimension_width_unit', 'value' => $settings['dimension']['width']['unit'], 'label' => \__('Width Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['dimension'], 'description' => \__('The frontend width input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_width_editable', 'value' => $settings['dimension']['width']['editable'], 'label' => \__('Width Editable', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'class' => 'checkbox _measurement_editable', 'description' => \__('Check this box to allow the needed width to be entered by the customer', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'dimension', 'input_name' => 'width', 'input_label' => \__('Width', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_dimension_width_options']);
\woocommerce_wp_text_input(['id' => '_measurement_dimension_width_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['dimension']['width']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Width Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '</div>';
echo '<hr/>';
// Dimension - Height
\WDFQVendorFree\fq_price_calculator_wp_radio(['name' => '_measurement_dimension', 'id' => '_measurement_dimension_height', 'rbvalue' => 'height', 'value' => 'yes' == $settings['dimension']['height']['enabled'] ? 'height' : '', 'class' => 'checkbox _measurement_dimension', 'label' => \__('Height', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Select to display the product height in the price calculator', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_dimension_height_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_dimension_height_label', 'value' => $settings['dimension']['height']['label'], 'label' => \__('Height Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Height input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_dimension_height_unit', 'value' => $settings['dimension']['height']['unit'], 'label' => \__('Height Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['dimension'], 'description' => \__('The frontend height input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_dimension_height_editable', 'value' => $settings['dimension']['height']['editable'], 'label' => \__('Height Editable', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'class' => 'checkbox _measurement_editable', 'description' => \__('Check this box to allow the needed height to be entered by the customer', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'dimension', 'input_name' => 'height', 'input_label' => \__('Height', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_dimension_height_options']);
\woocommerce_wp_text_input(['id' => '_measurement_dimension_height_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['dimension']['height']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Height Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '</div>';
echo '</div>';
