<?php

namespace WDFQVendorFree;

/**
 * @var \WPDesk\Library\FlexibleQuantityCore\WooCommerce\Settings $settings
 */
// Volume
echo '<div id="volume_measurements" class="measurement_fields">';
\woocommerce_wp_checkbox(['id' => '_measurement_volume_pricing', 'value' => $settings['volume']['pricing']['enabled'], 'class' => 'checkbox _measurement_pricing', 'label' => \__('Show Product Price Per Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to display product pricing per unit on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_volume_pricing_fields" class="_measurement_pricing_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_volume_pricing_label', 'value' => $settings['volume']['pricing']['label'], 'label' => \__('Pricing Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Label to display next to the product price (defaults to pricing unit)', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_volume_pricing_unit', 'value' => $settings['volume']['pricing']['unit'], 'class' => '_measurement_pricing_unit', 'label' => \__('Pricing Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['volume'], 'description' => \__('Unit to define pricing in', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume_pricing_calculator_enabled', 'class' => 'checkbox _measurement_pricing_calculator_enabled', 'value' => $settings['volume']['pricing']['calculator']['enabled'], 'label' => \__('Calculated Price', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define product pricing per unit and allow customers to provide custom measurements', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume_pricing_weight_enabled', 'value' => $settings['volume']['pricing']['weight']['enabled'], 'class' => 'checkbox _measurement_pricing_weight_enabled', 'wrapper_class' => $pricing_weight_wrapper_class . ' _measurement_pricing_calculator_fields', 'label' => \__('Calculated Weight', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define the product weight per unit and calculate the item weight based on the product volume', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume_pricing_inventory_enabled', 'value' => $settings['volume']['pricing']['inventory']['enabled'], 'class' => 'checkbox _measurement_pricing_inventory_enabled', 'wrapper_class' => 'stock_fields _measurement_pricing_calculator_fields', 'label' => \__('Calculated Inventory', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define inventory per unit and calculate inventory based on the product volume', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_overage_input('volume', $settings);
echo '</div>';
echo '<hr/>';
\woocommerce_wp_text_input(['id' => '_measurement_volume_label', 'value' => $settings['volume']['volume']['label'], 'label' => \__('Volume Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Volume input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_volume_unit', 'value' => $settings['volume']['volume']['unit'], 'label' => \__('Volume Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['volume'], 'description' => \__('The frontend volume input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume_editable', 'value' => $settings['volume']['volume']['editable'], 'label' => \__('Editable', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'class' => 'checkbox _measurement_editable', 'description' => \__('Check this box to allow the needed measurement to be entered by the customer', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'volume', 'input_name' => 'volume', 'input_label' => \__('Volume', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_volume_options']);
\woocommerce_wp_text_input(['id' => '_measurement_volume_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['volume']['volume']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Volume Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '</div>';
