<?php

namespace WDFQVendorFree;

/**
 * @var \WPDesk\Library\FlexibleQuantityCore\WooCommerce\Settings $settings
 */
// Volume (AxH)
echo '<div id="volume-area_measurements" class="measurement_fields">';
\woocommerce_wp_checkbox(['id' => '_measurement_volume-area_pricing', 'value' => $settings['volume-area']['pricing']['enabled'], 'class' => 'checkbox _measurement_pricing', 'label' => \__('Show Product Price Per Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to display product pricing per unit on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
echo '<div id="_measurement_volume-area_pricing_fields" class="_measurement_pricing_fields" style="display:none;">';
\woocommerce_wp_text_input(['id' => '_measurement_volume-area_pricing_label', 'value' => $settings['volume-area']['pricing']['label'], 'label' => \__('Pricing Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Label to display next to the product price (defaults to pricing unit)', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_volume-area_pricing_unit', 'value' => $settings['volume-area']['pricing']['unit'], 'class' => '_measurement_pricing_unit', 'label' => \__('Pricing Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['volume'], 'description' => \__('Unit to define pricing in', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume-area_pricing_calculator_enabled', 'class' => 'checkbox _measurement_pricing_calculator_enabled', 'value' => $settings['volume-area']['pricing']['calculator']['enabled'], 'label' => \__('Calculated Price', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define product pricing per unit and allow customers to provide custom measurements', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume-area_pricing_weight_enabled', 'value' => $settings['volume-area']['pricing']['weight']['enabled'], 'class' => 'checkbox _measurement_pricing_weight_enabled', 'wrapper_class' => $pricing_weight_wrapper_class . ' _measurement_pricing_calculator_fields', 'label' => \__('Calculated Weight', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define the product weight per unit and calculate the item weight based on the product volume', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\woocommerce_wp_checkbox(['id' => '_measurement_volume-area_pricing_inventory_enabled', 'value' => $settings['volume-area']['pricing']['inventory']['enabled'], 'class' => 'checkbox _measurement_pricing_inventory_enabled', 'wrapper_class' => 'stock_fields _measurement_pricing_calculator_fields', 'label' => \__('Calculated Inventory', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Check this box to define inventory per unit and calculate inventory based on the product volume', 'flexible-quantity-measurement-price-calculator-for-woocommerce')]);
\WDFQVendorFree\fq_price_calculator_overage_input('volume-area', $settings);
echo '</div>';
echo '<hr/>';
\woocommerce_wp_text_input(['id' => '_measurement_volume_area_label', 'value' => $settings['volume-area']['area']['label'], 'label' => \__('Area Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Area input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_volume_area_unit', 'value' => $settings['volume-area']['area']['unit'], 'label' => \__('Area Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['area'], 'description' => \__('The frontend area input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'volume-area', 'input_name' => 'area', 'input_label' => \__('Area', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_volume_area_options']);
\woocommerce_wp_text_input(['id' => '_measurement_volume_area_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['volume-area']['area']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Area Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '<hr/>';
\woocommerce_wp_text_input(['id' => '_measurement_volume_area_height_label', 'value' => $settings['volume-area']['height']['label'], 'label' => \__('Height Label', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \__('Height input field label to display on the frontend', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\woocommerce_wp_select(['id' => '_measurement_volume_area_height_unit', 'value' => $settings['volume-area']['height']['unit'], 'label' => \__('Height Unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'options' => $measurement_units['dimension'], 'description' => \__('The frontend height input field unit', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'desc_tip' => \true]);
\WDFQVendorFree\fq_price_calculator_attributes_inputs(['measurement' => 'volume-area', 'input_name' => 'height', 'input_label' => \__('Height', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'settings' => $settings, 'limited_field' => '_measurement_volume_area_height_options']);
\woocommerce_wp_text_input(['id' => '_measurement_volume_area_height_options', 'value' => \WDFQVendorFree\fq_price_calculator_get_options_value($settings['volume-area']['height']['options']), 'wrapper_class' => '_measurement_pricing_calculator_fields', 'label' => \__('Height Options', 'flexible-quantity-measurement-price-calculator-for-woocommerce'), 'description' => \WDFQVendorFree\fq_price_calculator_get_options_tooltip(), 'desc_tip' => \true]);
echo '</div>';
